version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - set.env

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"